AUTH_SECRET = 'AUTH_SECRET'
SECRET_KEY = 'SECRET_KEY'
AUTHORIZATION = "Authorization"
SQLALCHEMY_DATABASE_URI = 'SQLALCHEMY_DATABASE_URI'
UPLOAD_FOLDER = 'UPLOAD_FOLDER'
CONVERTED_FOLDER = 'CONVERTED_FOLDER'
ALLOWED_EXTENSIONS = 'ALLOWED_EXTENSIONS'
WRITER_PDF_EXPORT = 'WRITER_PDF_EXPORT'
DRAW_PDF_EXPORT = 'DRAW_PDF_EXPORT'
CALC_PDF_EXPORT = 'CALC_PDF_EXPORT'
IMPRESS_PDF_EXPORT = 'IMPRESS_PDF_EXPORT'
ENV = 'ENV'
CONTENT_TYPE = 'Content-type'
CONTENT_TYPE_JSON = 'application/json; charset=utf8'
CONTENT_TYPE_MULTIPART = 'multipart/form-data'
METHOD_POST = 'POST'
FCM_TOKEN = 'fcm_token'

# user
ID = 'id'
USER_ID = 'user_id'
FILE_ID = 'file_id'
DEVICE_ID = 'device_id'
USER_NAME = 'user_name'
EMAIL = 'email'
PHOTO = 'photo'

# conversion
FILE = 'file'
TO_EXT = "to_ext"

# Push Notification
TITLE = "title"
BODY = 'body'
NOTIFICATION_ID = "notification_id"
